services:
  frontend:
    build:
      context: frontend
      target: development
    image: frontend:latest
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0

  backend:
    restart: always
    build:
      context: backend
      target: development
    image: backend:latest
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000
      - 9229 # for debugging
    ports:
      - 3001:3000
      - 9229:9229 # for debugging
    environment:
      - NODE_ENV=production

  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
