name: Deploy to Heroku

on:
  push:
    branches:
      - main  # mainブランチへのプッシュでデプロイが実行
  workflow_dispatch:  # 手動トリガーを追加

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com || exit 1

      - name: Install dependencies
        run: npm install
  
      - name: Build React app
        run: npm run build

      - name: Build and push Docker images with compose
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          # docker-composeでビルド
          docker-compose -f docker-compose.yml build

      - name: List built Docker images
        run: |
          # イメージがビルドされているか確認
          docker images

      - name: Tag and push frontend:latest image
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker tag frontend:latest registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Tag and push backend image
        env:
         HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker tag backend:latest registry.heroku.com/$HEROKU_APP_NAME/backend
          docker push registry.heroku.com/$HEROKU_APP_NAME/backend

      - name: Release on Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app $HEROKU_APP_NAME